### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Blueberryy**
Just a copy from workshop :P

### CODE REVIEW

**Comment by nuke-haus** [comment]
looks good, did you do a test run with this code to make sure nothing broke?

**Comment by Blueberryy** [comment]
Yes. You can look into this in my fork https://github.com/Blueberryy/redead

**Comment by nuke-haus** [comment]
why is this closed? i could merge it into the trunk if it works.

**Comment by Blueberryy** [comment]
Because i made updates in my and not finished my version fully. If you going merge currect version, gamemode will be unstable

**Pull request closed without merging**
